package Main;

import javax.swing.text.Caret;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class Errores extends javax.swing.JDialog {

    /**
     * Creates new form Errores
     */
    public Errores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Errores(java.awt.Frame parent, boolean modal,String [] lineas) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        GetSeleccion(lineas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLblError = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaErrores = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLblError.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblError.setText("Porfavor corrija lo que se le indica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLblError)
                .addGap(157, 157, 157))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLblError)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        txtAreaErrores.setColumns(20);
        txtAreaErrores.setRows(5);
        txtAreaErrores.setFocusable(false);
        jScrollPane2.setViewportView(txtAreaErrores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Errores dialog = new Errores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void GetSeleccion (String []lineas){
       
        
        String [] Errores;
        String con="";
        for (int i = 1; i < lineas.length; i++) {
            String sError="";
            
            Errores=lineas[i].split("-");
            switch(Errores[2]){
                case " e003 ": sError= "NombreCualquiera.Initialize(Camera{ \"Codigo\" });";
                break;
                case " e004 ": sError= "NombreCualquiera.Initialize(Camera{ \"Codigo\" });";
                break;
                case " e005 ": sError= "NombreCualquiera.Initialize(Camera{ \"Codigo\" });";
                break;
                case " e006 ": sError= "TipoDeDato NombreVariable = AsignaciónTipoVariable; || TipoDeDato NombreVarible; || NombreVariable = AsignaciónTipoVariable;";
                break;
                case " e007 ": sError= "ValorTipoVariable Operador ValorTipoVariable;";
                break;
                case " e008 ": sError= "(Parametros)";
                break;
                case " e009 ": sError= "...";
                break;
                case " e010 ": sError= "Enable();";
                break;
                case " e011 ": sError= "Program(ValorEntero,ValorEntero);";
                break;
                case " e012 ": sError= "IsOn(); || IsMove(); || Move(NumeroEntero,NumeroEntero); ...";
                break;
                case " e013 ": sError= "Receive();";
                break;
                case " e014 ": sError= "If(Condicion){\"Codigo\"}";
                break;
                case " e015 ": sError= "If(Condicion){\"Codigo\"}";
                break;
                case " e016 ": sError= "TipoDeDato NombreVariable = AsignaciónTipoVariable; || TipoDeDato NombreVarible; || NombreVariable = AsignaciónTipoVariable;";
                break;
                case " e017 ": sError= "If(Condicion) {\"Codigo\"}";
                break;
                case " e018 ": sError= "No Repetir variables ya declaradas";
                break;
                case " e019 ": sError= "TipoDeDato NombreVariable = AsignaciónTipoVariable; || TipoDeDato NombreVarible; || NombreVariable = AsignaciónTipoVariable;";
                break;
                case " e020 ": sError= "NombreVariable = AsignaciónTipoVariable;";
                break;
                case " e021 ": sError= "ValorTipoVariable Operador ValorTipoVariable;";
                break;
            }
            con =con+""+ Errores[0] + " " + Errores[1] + " " + Errores[2] + "\nCorregir como: " + sError + "\n\n";    
        }
       txtAreaErrores.setText(con);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaErrores;
    // End of variables declaration//GEN-END:variables
}
